macrocosm-os/finetuning

- competitions/utils.py
- constants/__init__.py
- finetune/mining.py
- finetune/model.py
- model/model_updater.py
- model/storage/hugging_face/hugging_face_model_store.py
- neurons/miner.py
- neurons/validator.py
- requirements.txt
- scripts/model_validation.py
- scripts/upload_model.py
- tests/competitions/test_utils.py
- tests/finetune/test_mining.py
- tests/model/test_model_updater.py
Announcing Release 1.0.1.
This release includes a few fixes as well as refactoring to allow the competition schedule to change based on block.
This  is the first step in adding new competitions with different parameters and evaluation strategies. Stay tuned for more on this soon!
Subnet Improvements
- Competition Schedule is now based on the current block.
- Flash-attn requirement has been un-pinned. This should resolve issues with imports here. Please 
run python3 -m pip install flash-attn --upgrade to upgrade to the latest if this affected you.
Validator Improvements
- Fixed bug when outputting the step table log to wandb.
> Release 1.0.1

- model/model_updater.py
- neurons/validator.py
- tests/model/test_model_updater.py
We currently log twice if a we fail to sync a model for a UID. First as a trace log inside the ModelUpdater and then once as an error log in the exception handler of the update loop.
This changes that to just 1 trace log for expected errors due to miner misconfiguration
> Reduce logging noise for expected "errors" in update loop

- constants/__init__.py
- docs/miner.md
- docs/validator.md
- neurons/config.py
- neurons/miner.py
- requirements.txt
- tests/competitions/test_utils.py
From testing against the current competition flash attention improves the inference speed by about 30%.
However given that we still have to load each model as well, the total improvement for evaluating a model is only about 20%. In absolute values, it is only about ~4.5 minutes to fully load and evaluate a model which is more than enough to get through all the models each epoch.
To simplify requirements and code, flash attn was also removed from the miner in this change, although they would be welcome to add it back in for their custom training code as the default mining code would not be competitive either way.
> Remove flash attn.

- constants/__init__.py
- neurons/validator.py
- requirements.txt
- Define a per competition max model size.
- Define a per competition Epsilon Func (currently unused)
- Use the taoverse repo name helper.
- Bump state version as there is a breaking change to the state of the model tracker.
- Bump overall version to 1.2.0 in preparation for upcoming release.
> Bump taoverse to 1.0.5.

- competitions/data.py
- constants/__init__.py
- finetune/datasets/subnet/cortex_subset_loader.py
- finetune/datasets/subnet/prompting_subset_loader.py
- finetune/validation.py
- neurons/config.py
- neurons/validator.py
- scripts/model_validation.py
- tests/finetune/test_graph.py
- tests/finetune/test_mining.py
Adds a new B7_MULTI_CHOICE competition.
- Weights are annealed slowly from a 100/0 split to a 50/50 split at a rate of 5% per 3600 blocks.
- Multiple choice question data is loaded from the PromptingSubnetLoader which pulls from SN1 wandb logs.
- Evaluation asks the models the multiple choice questions and takes the first possible answer returned.
Across all competitions we only keep the 2 top models from eval to eval to speed up the evaluation loop.
Across all competitions we will start using an epsilon with a linear decay instead of a fixed epsilon value.
> Add B7_MULTI_CHOICE competition.

- constants/__init__.py
- finetune/validation.py
- neurons/config.py
- neurons/validator.py
For multiple-choice competitions, applies the epsilon to the models total deviation rather than per-answer deviation. The latter meant a model would "beat" all later models on questions where they were both incorrect.
Additionally, increased the number of models to eval and increased the sample size to 400. In practice, we only get about 225 samples.
> Address win rate bug for competition 2

- constants/__init__.py
Since Comp 2 deviations are between 0 and 1 instead of the tighter range of expected loss for competition 1 we use a larger relative epsilon value.
Also shorten the time to full decay to adjust to that further gap between start and end epsilon.
> Bump to 2.0.1 and increase epsilon for Comp 2.

- constants/__init__.py
- finetune/datasets/subnet/history_scan.py
- finetune/datasets/subnet/prompting_subset_loader.py
- neurons/config.py
- requirements.txt
There are currently 7 running runs in the prompting wandb prompting. One of those runs (hhodrv2s) is poisoned and all attempts to perform a history scan on it result in a 502 from wandb. Furthermore, the wandb client will INFINITELY RETRY, which is ridiculous.
This change addresses the issue in 2 ways:
1. We reimplement the wandb history client so we can add a sane amount of retries (3). We combine this with a reduction in collected samples to 300, to make it more likely we'll fulfill the 300 samples from 6 runs, should one be poisoned in future.
2. We also use a sampled history scan, which additionally filters (server-side) the steps returned to only those that contain the requested keys. The returned steps also only contain the requested metrics. As a result, it now takes a few seconds …
> Wandb hotfix

- constants/__init__.py
- finetune/datasets/subnet/history_scan.py
- finetune/datasets/subnet/prompting_subset_loader.py
- neurons/config.py
- requirements.txt
Hotfix release to address the wandb issue that causes the main thread to hang indefinitely.
There are currently 7 running runs in the prompting wandb prompting. One of those runs (hhodrv2s) is poisoned and all attempts to perform a history scan on it result in a 502 from wandb. Furthermore, the wandb client will INFINITELY RETRY, which is ridiculous.
This change addresses the issue in 2 ways:
1. We reimplement the wandb history client so we can add a sane amount of retries (3). We combine this with a reduction in collected samples to 300, to make it more likely we'll fulfill the 300 samples from 6 runs, should one be poisoned in future.
2. We also use a sampled history scan, which additionally filters (server-side) the steps returned to only those that contain the requested keys. The …
> Release 2.1.1

- neurons/miner.py
The method signature in fintetune.mining is as follows:
```
async def load_best_model(
download_dir: str,
competition_id: CompetitionId,
metagraph: Optional[bt.metagraph] = None,
metadata_store: Optional[ModelMetadataStore] = None,
remote_model_store: Optional[RemoteModelStore] = None,
) -> PreTrainedModel:
```
> Fix argument order in miner for load best.

- constants/__init__.py
- finetune/__init__.py
- finetune/datasets/subnet/prompting_subset_loader.py
- finetune/utils.py
- neurons/config.py
- neurons/validator.py
- scripts/model_validation.py
- tests/finetune/test_utils.py
V-trust improvements:
1. Improving the dataset loader to get more samples (No longer use "MultiChoiceRewardModel_rewards" which was causing a lot of samples to be dropped by wandb. I don't know why)
2. Aligning validator evaluations to "sync blocks" to reduce the variance in evaluations performed across validators
3. Switch to a WTA weight rather than softmax
4. Set weight to 0 for models with very little weight
Other improvements:
1. Correctly handle set_weight errors
2. Since we're now rate limiting eval loops, increases the number of models per loop to 20.
> Improve vtrust

- constants/__init__.py
- neurons/validator.py
Adjust alpha to 0.05 and min weight threshold to 0.1.
In a situation with only one clearly winning model that means:
1) It takes 3 cycles of winning in a row to go from 0 weight to 0.143 weight and cross the 0.1 threshold.
2) It takes 45 cycles of winning in a row to go from 0 weight to 0.901 weight and ensure no other models have >= 0.1 weight.
3) As a corollary to 2) that means if a model has 1 weight, it takes 45 cycles to drop below 0.1 weight.
Note: Temperature is no longer used in this subnet and the constant for it was also removed in this change.
> Adjust alpha and min weight threshold.

- neurons/validator.py
This call seems to fail more frequently on 8.4.3. After adding retries, I no longer saw this fail (all 5 attempts)
> Add retries to fetching the block

- scripts/run_benchmarks.py
- This bug was preventing the benchmarks from running on comp 3
> Benchmarks: Use the provided tokenizer for INSTRUCT_8B

- finetune/utils.py
- neurons/validator.py
- tests/finetune/test_utils.py
To my surprise, hash() is not deterministic across sessions...
Switch over to hashlib which is deterministic.
> Fix seed used across valis

- constants/__init__.py
- docs/examples.ipynb
- finetune/utils.py
- neurons/config.py
- neurons/validator.py
- scripts/model_validation.py
- scripts/upload_model.py
- tests/finetune/test_utils.py
- Sunset the B7_MULTI_CHOICE at block 4_675_163 and giving full weight to INSTRUCT_8B.
- The IFEval evaluation task weight is increased to 20% at block 4_675_163 and weight on MMLU has decreased to 65%
- Fixed a bug causing the random seeds to differ across validators (it turns out python's hash() function isn't deterministic across sessions/machines...who knew? 🤔 ). This should reduce model evaluation variance and improve vTrust.
> Release 2.8.0

- neurons/validator.py
1) Adjust set weight retry from 1 to 2 minutes.
2) Wait 3 minutes on websocket.exceptions.InvalidStatus during the update loop to handle 429 or other errors.
> Send subtensor requests less aggressively.

- constants/__init__.py
Taking this change from #200 as a hotfix
> Reduces min subnet 1 validator stake from 100k to 10k to increase the rate of synthetic benchmarks.
> This change is necessary because of the subnet stake changes due to DTAO.
> Release 2.9.2

- constants/__init__.py
- finetune/datasets/generated/if_eval_loader.py
- finetune/datasets/generated/mmlu_parser.py
- finetune/datasets/hugging_face/macrocosmos_dataset_loader.py
- neurons/validator.py
We now use all samples available from the Macrobench dataset.
This means that:
- We now sample 10 configs from the entire Macrobench dataset to create a subset, and choose `max_samples` out of all the samples available in the subset.
- `eval_block_delay` is now irrelevant, set to 1.
- epsilon now decays over a single day, to accommodate this temporary competition. 
- New task weights are: SYNTHETIC_MMLU: 30%, WORD_SORTING: 5%, FINEWEB: 35%, IF_EVAL_V2: 30%
> Adapting to slower SN1 - SYNTHETIC_MMLU generation

- constants/__init__.py
- finetune/datasets/generated/mmlu_parser.py
- finetune/datasets/generated/word_sorting_loader.py
- finetune/eval/if_eval/sentence_count.py
- finetune/eval/method.py
- neurons/validator.py
Removed unnecessary arguments from `check_for_reasonable_output()` calls
Avoided silent excepts.
> Redoing messed up PR

- constants/__init__.py
- neurons/validator.py
- Fixing bug where number of eval tasks and samples didn't match.
- Added eos as default pad token when none is available in the model's own tokenizer.
> Hotfix - Handling case when we use model's own tokenizer.

- constants/__init__.py
- neurons/validator.py
- Decreased `eval_block_delay` 
- Fixed bug that kept evaluating models from inactive competitions.
- Fixed huge rain of useless logs.
- Version and vali state bump.
> Validator hotfix
